name: CFSDev based on .NET Core 6.0.x

on:
  push:
    branches: ["release", "master"]
  pull_request:
    branches: ["release", "master"]

env:
  SOLUTION: CFSDev.sln  # Replace with your solution name, i.e. CFSDev.sln.
  DOTNET_VERSION: 6.0.x # Replace with your .NET version, i.e. 6.0.x.

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      # Restore CFSDev solution
      - name: Restore solution
        run: msbuild ${{env.SOLUTION}} /t:Restore -p:RestorePackagesConfig=true

      # Build CFSDev solution
      - name: Build solution
        run: dotnet build
      
      # Build CFSDev solution
      - name: xUnit Tests
        run: dotnet test --no-build --no-restore
